# Generated by Django 4.2.5 on 2023-09-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_visiting"),
    ]

    operations = [
        migrations.AddField(
            model_name="places",
            name="imgage",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="visiting",
            name="imgage",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
